try {
  2 + 2;
} catch {
  'no error';
}
